### ISSUE TITLE
Zadanie 1

### ISSUE THREAD

**Issue by rflw** [joka888/r1#3]
Usuń elementy `<input...` z html i wstaw je korzystając z `javascript`

**Comment by joka888** [comment]
``

**Comment by joka888** [comment]
`var btnMinus = document.createElement("input");
btnMinus.classList.add('btnMinus');
btnMinus.setAttribute("type", "button");
btnMinus.setAttribute("value", "-");

var btnPlus = document.createElement("input");
btnPlus.classList.add('btnPlus');
btnPlus.setAttribute("type", "button");
btnPlus.setAttribute("value", "+");

var number = document.createElement("input");
number.classList.add('number');
number.setAttribute("type", "text");
number.setAttribute("value", "0");

var spinner = document.querySelector('.spinner')
spinner.appendChild(btnMinus);
spinner.appendChild(number);
spinner.appendChild(btnPlus);`

**Comment by rflw** [comment]
👌
